# Generated by Django 3.2.5 on 2022-09-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsRepo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='difficulty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='anglesForce',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='eloScore',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='supportsForce',
            field=models.IntegerField(null=True),
        ),
    ]
