# Generated by Django 3.2.5 on 2022-09-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsRepo', '0002_auto_20220907_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='statement_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
