# Generated by Django 3.2.5 on 2022-09-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsRepo', '0005_alter_homework_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='statement_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
