# Generated by Django 3.2.5 on 2022-09-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsRepo', '0006_alter_homework_statement_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='Fm',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='Fx',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='Fy',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
