# Generated by Django 3.2.5 on 2022-09-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsRepo', '0009_auto_20220924_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='anglesForce',
            new_name='angles_force',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='eloScore',
            new_name='elo_score',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='supportsForce',
            new_name='supports_force',
        ),
    ]
