# Generated by Django 3.2.5 on 2022-09-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsRepo', '0012_auto_20220925_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
