# Generated by Django 3.2.5 on 2022-09-25 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsRepo', '0013_rename_name_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='angles_force',
            new_name='angles_score',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='supports_force',
            new_name='supports_score',
        ),
    ]
