# Generated by Django 3.2.5 on 2022-09-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsRepo', '0014_auto_20220925_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='diagram2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
