# Generated by Django 3.2.5 on 2022-09-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsRepo', '0015_homework_diagram2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
